/*
 * mpmcm_registers.c
 *
 *  Created on: 15 dec. 2024
 *      Author: Ludo
 */

#include "mpmcm_registers.h"

#include "common_registers.h"
#include "types.h"
#include "una.h"

/*** MPMCM REGISTERS local macros ***/

#define MPMCM_CHANNEL_DATA(error_value) \
    { \
        UNA_REGISTER_ACCESS_READ_ONLY, \
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS, \
        UNA_REGISTER_RESET_VALUE_STATIC, \
        error_value \
    }, \

#define MPMCM_CHANNEL_REGISTER \
    /* ACTIVE_POWER_0 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0))) \
    /* ACTIVE_POWER_1 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0))) \
    /* RMS_VOLTAGE_0 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0))) \
    /* RMS_VOLTAGE_1 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0))) \
    /* RMS_CURRENT_0 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_CURRENT_ERROR_VALUE << 16) | (UNA_CURRENT_ERROR_VALUE << 0))) \
    /* RMS_CURRENT_1 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_CURRENT_ERROR_VALUE << 16) | (UNA_CURRENT_ERROR_VALUE << 0))) \
    /* APPARENT_POWER_0 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0))) \
    /* APPARENT_POWER_1 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_ELECTRICAL_POWER_ERROR_VALUE << 16) | (UNA_ELECTRICAL_POWER_ERROR_VALUE << 0))) \
    /* POWER_FACTOR_0 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_POWER_FACTOR_ERROR_VALUE << 16) | (UNA_POWER_FACTOR_ERROR_VALUE << 0))) \
    /* POWER_FACTOR_1 */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_POWER_FACTOR_ERROR_VALUE << 16) | (UNA_POWER_FACTOR_ERROR_VALUE << 0))) \
    /* ENERGY */ \
    MPMCM_CHANNEL_DATA((uint32_t) ((UNA_ELECTRICAL_ENERGY_ERROR_VALUE << 16) | (UNA_ELECTRICAL_ENERGY_ERROR_VALUE << 0))) \

/*** MPMCM REGISTERS global variables ***/

const UNA_register_t MPMCM_REGISTER[MPMCM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER
    /* FLAGS_1 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* FLAGS_2 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* CONFIGURATION_0 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_NVM,
        0x00000000
    },
    /* CONFIGURATION_1 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_NVM,
        0x00000000
    },
    /* CONFIGURATION_2 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_NVM,
        0x00000000
    },
    /* CONFIGURATION_3 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_NVM,
        (uint32_t) (UNA_TIME_ERROR_VALUE << 0)
    },
    /* STATUS_1 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* CONTROL_1 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        5000,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* MAINS_FREQUENCY_0 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) ((UNA_MAINS_FREQUENCY_ERROR_VALUE << 16) | (UNA_MAINS_FREQUENCY_ERROR_VALUE << 0)),
    },
    /* MAINS_FREQUENCY_0 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) ((UNA_MAINS_FREQUENCY_ERROR_VALUE << 16) | (UNA_MAINS_FREQUENCY_ERROR_VALUE << 0)),
    },
    /* CH1 */
    MPMCM_CHANNEL_REGISTER
    /* CH2 */
    MPMCM_CHANNEL_REGISTER
    /* CH3 */
    MPMCM_CHANNEL_REGISTER
    /* CH4 */
    MPMCM_CHANNEL_REGISTER
    /* TIC */
    MPMCM_CHANNEL_REGISTER
};
