/*
 * rrm_registers.c
 *
 *  Created on: 15 dec. 2024
 *      Author: Ludo
 */

#include "rrm_registers.h"

#include "common_registers.h"
#include "types.h"
#include "una.h"

/*** RRM REGISTERS global variables ***/

const UNA_register_t RRM_REGISTER[RRM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER
    /* FLAGS_1 */
    UNA_GENERATE_REGISTER(
        UNA_REGISTER_ACCESS_READ_ONLY,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS
    ),
    /* CONFIGURATION_0 */
    UNA_GENERATE_REGISTER(
        UNA_REGISTER_ACCESS_READ_WRITE,
        UNA_REGISTER_RESET_VALUE_NVM,
        (uint32_t) (UNA_CURRENT_ERROR_VALUE << 0),
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS
    ),
    /* STATUS_1 */
    UNA_GENERATE_REGISTER(
        UNA_REGISTER_ACCESS_READ_ONLY,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) (UNA_BIT_ERROR << 0),
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS
    ),
    /* CONTROL_1 */
    UNA_GENERATE_REGISTER(
        UNA_REGISTER_ACCESS_READ_WRITE,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000,
        5000
    ),
    /* ANALOG_DATA_1 */
    UNA_GENERATE_REGISTER(
        UNA_REGISTER_ACCESS_READ_ONLY,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0)),
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS
    ),
    /* ANALOG_DATA_2 */
    UNA_GENERATE_REGISTER(
        UNA_REGISTER_ACCESS_READ_ONLY,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) (UNA_CURRENT_ERROR_VALUE << 0),
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS
    )
};
