/*
 * uhfm_registers.c
 *
 *  Created on: 15 dec. 2024
 *      Author: Ludo
 */

#include "uhfm_registers.h"

#include "common_registers.h"
#include "types.h"
#include "una.h"

/*** UHFM REGISTERS global variables ***/

const UNA_register_t UHFM_REGISTER[UHFM_REGISTER_ADDRESS_LAST] = {
    COMMON_REGISTER
    /* CONFIGURATION_0 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_NVM,
        (uint32_t) ((0b111 << 10) | (UNA_RF_POWER_ERROR_VALUE << 0))
    },
    /* CONFIGURATION_1 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_NVM,
        0xFFFFFFFF
    },
    /* STATUS_1 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) (UNA_RF_POWER_ERROR_VALUE << 8)
    },
    /* CONTROL_1 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        60000,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) (UNA_RF_POWER_ERROR_VALUE << 17)
    },
    /* CONTROL_1 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0xFFFFFFFF
    },
    /* ANALOG_DATA_1 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        (uint32_t) ((UNA_VOLTAGE_ERROR_VALUE << 16) | (UNA_VOLTAGE_ERROR_VALUE << 0))
    },
    /* SIGFOX_EP_ID */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* SIGFOX_UL_PAYLOAD_0 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* SIGFOX_UL_PAYLOAD_1 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* SIGFOX_UL_PAYLOAD_2 */
    {
        UNA_REGISTER_ACCESS_READ_WRITE,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* SIGFOX_DL_PAYLOAD_0 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    },
    /* SIGFOX_DL_PAYLOAD_1 */
    {
        UNA_REGISTER_ACCESS_READ_ONLY,
        DINFOX_REGISTERS_DEFAULT_TIMEOUT_MS,
        UNA_REGISTER_RESET_VALUE_STATIC,
        0x00000000
    }
};
